create table course(
    course_ID  int not null,
    user_ID int not null,
    courseName varchar(120) not null,
    term int null,
    startDate date not null,
    endDate date not null,
primary key(course_ID),
foreign key (user_ID) references users (user_ID)
);

create table student(
Student_ID int not null ,
stdName varchar(100) not null,
email varchar(150) not null unique,
primary key (student_Id)
);

create table courseEvet(
    event_ID  number generated by default as identity,
    course_ID  int not null,
    eventType varchar2(20),
    dueDate date not null,
    status varchar2(20) not null,
    primary key (event_ID),
    foreign key (course_ID) references course(course_ID),
    check (eventType in ('Assignment','Project','MidTerm','Quiz','Final'))
    )

    create table topic(
    plan_ID  int not null,
    course_ID  int not null,
    student_ID  int not null,
    ScheduledStart date NOT NULL,
    ScheduledEnd date NOT NULL,
    PlanStatus varchar2(20) NOT NULL,
    primary key (plan_ID),
    foreign key (course_ID) references course(course_ID),
     foreign key (student_ID) references student(student_ID),
    check (ScheduledEnd>ScheduledStart)
)

create table studyPlanItem(
    plan_ID  int not null,
    course_ID  int not null,
    student_ID  int not null,
    ScheduledStart date NOT NULL,
    ScheduledEnd date NOT NULL,
    PlanStatus varchar2(20) NOT NULL,
    primary key (plan_ID),
    foreign key (course_ID) references course(course_ID),
     foreign key (student_ID) references student(student_ID),
    check (ScheduledEnd>ScheduledStart))

    create table AvailableBlocks(
    blocks_ID  int not null,
    student_ID  int not null,
    DayofWeek varchar(10)  NOT NULL,
    StartTime date NOT NULL,
     EndTime date NOT NULL,

    primary key (blocks_ID),
     foreign key (student_ID) references student(student_ID),
    check (EndTime>StartTime)
)

create table StudySession(
    session_ID  int not null,
    student_ID  int not null,
    topic_ID  int not null,
    StartTime date NOT NULL,
    EndTime date NOT NULL,
focusScore varchar2(1),
    primary key (session_ID),
     foreign key (student_ID) references student(student_ID),
     foreign key (topic_ID) references topic(topic_ID),
    check (EndTime>StartTime),
    check (focusScore in ('1','2','3','4','5'))
)